networks:
  grafana:

services:
  grafana-plugin-dev:
    build: .
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 3000:3000
      - 3222:3222
    networks:
      - grafana
    container_name: grafana-plugin-dev
    command: --config /var/lib/grafana/config.ini
    volumes:
      - ./data/grafana-oss:/var/lib/grafana
      - ./config/config.ini:/var/lib/grafana/config.ini
      - ../../:/var/lib/grafana/plugins/sasesp-plugin
