apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
          {
              "id": 1,
              "uid": "afu6f0e4rx4hse",
              "orgId": 1,
              "name": "sasesp-plugin",
              "type": "sasesp-plugin",
              "typeName": "SAS Event Stream Processing",
              "typeLogoUrl": "public/plugins/sasesp-plugin/img/logo.svg",
              "access": "proxy",
              "url": "https://sas-event-stream-processing-studio-app/SASEventStreamProcessingStudio",
              "user": "",
              "database": "",
              "basicAuth": false,
              "isDefault": true,
              "jsonData": {
                  "oauthPassThru": true,
                  "pdcInjected": false,
                  "tlsSkipVerify": true
              },
              "readOnly": false
          },
          {
              "id": 1,
              "uid": "afu6f0e4rx4hse",
              "orgId": 1,
              "name": "sasesp-plugin",
              "type": "sasesp-plugin-manager",
              "typeName": "SAS Event Stream Manager",
              "typeLogoUrl": "public/plugins/sasesp-plugin/img/logo.svg",
              "access": "proxy",
              "url": "https://sas-event-stream-manager-app/SASEventStreamManager",
              "user": "",
              "database": "",
              "basicAuth": false,
              "isDefault": true,
              "jsonData": {
                  "oauthPassThru": true,
                  "pdcInjected": false,
                  "tlsSkipVerify": true
              },
              "readOnly": false
          },
      ]
    }