name: Run Snyk Scan

on:
  workflow_dispatch:
    inputs:
      SNYK_API_KEY:
        description: 'Snyk API Key needed to run security scan'
        required: true
        type: string

jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
      # shallow clone doesn't fetch tags, so cdp-release-management plugin doesn't work without this
          fetch-depth: 0
    - name: Run Snyk
      shell: bash
      run: |
          set -e
          npx snyk auth ${{ inputs.SNYK_API_KEY }} && set +x
          npx snyk code test --sarif > sast.sarif
          echo "SAST scan complete with no security issues"
          npx snyk test --sarif > sca.sarif
          echo "SCA scan complete with no security issues"
    - name: Upload SAST scans
      uses: actions/upload-artifact@v4
      if: always() 
      with:
          path: sast.sarif
          name: sast
    - name: Upload SCA scans
      uses: actions/upload-artifact@v4
      if: always()
      with:
          path: sca.sarif
          name: sca
