name: Run Snyk Scan

on:
  workflow_dispatch:
    inputs:
      SNYK_API_KEY:
        description: 'Snyk API Key needed to run security scan'
        required: true
        type: string

jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
      # shallow clone doesn't fetch tags, so cdp-release-management plugin doesn't work without this
          fetch-depth: 0
    - name: Mask Password
      run: |
        API_PASSWORD=$(jq -r '.inputs.SNYK_API_KEY' $GITHUB_EVENT_PATH)
        echo ::add-mask::$API_PASSWORD
        echo API_PASSWORD=$API_PASSWORD >> $GITHUB_ENV
    - name: Run Snyk
      id: snyk
      shell: bash
      run: |
          set -e
          scanError=false
          npx snyk auth ${{ env.API_PASSWORD }} && set +x
          npx snyk code test --sarif > sast.sarif || scanError=true
          echo "SAST scan complete"
          npx snyk test --sarif > sca.sarif || scanError=true
          echo "SCA scan complete"
          if [ "$scanError" = true ] ; then
            exit 1
          fi
    - name: Update summary success message
      if: success()
      run: echo '✅ Snyk Scans completed without any security concerns!' >> $GITHUB_STEP_SUMMARY
      
    - name: Update summary with security issues
      if: failure()
      run: echo '❌ Snyk Scans completed with some security issues. Check Scan results for more details!' >> $GITHUB_STEP_SUMMARY
    
    - name: Upload SAST scans
      uses: actions/upload-artifact@v4
      if: always() 
      with:
          path: sast.sarif
          name: sast
    
    - name: Upload SCA scans
      uses: actions/upload-artifact@v4
      if: always()
      with:
          path: sca.sarif
          name: sca
