name: Run Snyk Scan

on:
  workflow_dispatch:
    inputs:
      SNYK_API_KEY:
        description: 'Snyk API Key needed to run security scan'
        required: true
        type: string

jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
      # shallow clone doesn't fetch tags, so cdp-release-management plugin doesn't work without this
          fetch-depth: 0
    - name: Run Snyk
      shell: bash
      run: |
          echo $(ls)
          set -e
          npx snyk auth ${{ inputs.SNYK_API_KEY }} && set +x
          declare -a directoriesToScan=(
          	src
            pkg
            internal
          )
          rm -rf ./include/
          for includedDir in ${directoriesToScan[*]}
          do
          	mkdir -p $(dirname ./include/$includedDir)
          	target=$(realpath ../$includedDir)
            echo $target
          	ln -s $target ./include/$includedDir
          done
          cd ./include/ # Snyk can't handle scanning properly unless scanning inside the current directory.
          echo $(ls)
          cd src
          echo "Inside include/src"
          echo $(ls)
          cd ..
          # npx snyk code test --json | npx snyk-to-html -o ../report.html
          npx snyk code test --json
          cd ../
          rm -rf ./include
