name: Run Snyk Scan

on:
  workflow_dispatch:
    inputs:
      SNYK_API_KEY:
        description: 'Snyk API Key needed to run security scan'
        required: true
        type: string

jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
      # shallow clone doesn't fetch tags, so cdp-release-management plugin doesn't work without this
          fetch-depth: 0
    - name: Run Snyk
      shell: bash
      run: |
          echo $(ls)
          cd ./src 
          echo $(ls)
          cd ..
          set -e
          npx snyk auth ${{ inputs.SNYK_API_KEY }} && set +x
          echo "SCA scan:"
          npx snyk test --sarif
          echo "SAST scan:"
          npx snyk code test --sarif
